version: '2'
services:
  web:
    image: odoo:8.0
    depends_on:
       - db
    ports:
       - "8069:8069"
    volumes:
       - odoo8-web-data:/var/lib/odoo
       - ./addons:/mnt/extra-addons
  db:
    image: postgres:9.4
    environment:
       - POSTGRES_PASSWORD=odoo
       - POSTGRES_USER=odoo
       - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
       - odoo8-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo8-web-data:
  odoo8-db-data:
